# Percolation

Consider a $n \times n$ grid of squares. Each square is either "open" with probability $p$ or "closed" with probability $1-p$. A liquid is poured on the top of the grid. What is the probability that the liquid will be able to flow from the top of the grid to the bottom through a path of open squares? 

Import some necessary modules:

In [0]:
import random
import numpy
import math

Define variables:

* `n`: the number of rows and columns in the grid
* `p`: probability that a square is "open"

In [0]:
n = 10
p = 0.5


Define a data structure for the $n \times n$ grid. You will need to decide how to represent "open" and "closed" squares in memory. Fill your grid so that each square is "open" with probability $p$.

In [0]:
numpy.random.rand(10,10) < p
# test each element to see whether its less than p 



array([[ True,  True, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False, False,  True,  True,  True, False,
        False],
       [ True, False,  True,  True,  True, False, False,  True,  True,
         True],
       [False,  True,  True,  True,  True, False, False, False,  True,
         True],
       [ True,  True,  True,  True, False, False,  True,  True, False,
        False],
       [False,  True, False, False,  True, False, False, False,  True,
        False],
       [ True, False, False, False, False, False,  True,  True,  True,
        False],
       [False,  True, False, False, False,  True, False,  True,  True,
        False],
       [ True,  True,  True, False, False,  True, False,  True, False,
         True],
       [ True, False, False,  True, False, False, False,  True, False,
         True]])

In [0]:
q=random.choices([0,1],[0.5,0.5], k=10) ## 0 means closed, 1 means open


[0, 1, 0, 0, 1, 1, 1, 0, 1, 1]

In [0]:
numpy.random.choice([0,1], p=[0.5,0.5],size=(n,n))

array([[0, 0, 1, 1, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 1, 0, 1]])

In [0]:
grid = numpy.zeros((n,n))
for i in range(n):
    for j in range(n):
      r = random.random()
      if(r < p):
        grid[i,j] = 1
grid 

array([[1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 1., 0., 0., 1., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 1.],
       [0., 1., 1., 1., 0., 0., 1., 0., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 1., 0., 1., 1., 0., 1., 1., 0., 0.],
       [0., 1., 1., 0., 1., 1., 1., 0., 1., 0.],
       [0., 1., 1., 1., 1., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 1., 1., 0., 0., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 1., 0., 0.]])

Now we need to determine whether there exists a path of open cells from the top to the bottom of the grid.

_How should we do this? What sort of algorithm would work best?_