# Percolation: Recursive Depth-First Search

Consider a $n \times n$ grid of squares. Each square is either "open" with probability $p$ or "closed" with probability $1-p$. A liquid is poured on the top of the grid. What is the probability that the liquid will be able to flow from the top of the grid to the bottom through a path of open squares? 

## Setup

Import some necessary modules:

In [0]:
import random
import math
import numpy

Define variables:

* `n`: the number of rows and columns in the grid
* `p`: probability that a square is "open"

In [0]:
n = 10
p = 0.7

Define a data structure for the $n \times n$ grid. Here, we use a numpy 2D array, each entry of which is either 0 or 1. Suppose that 0 represents an open square  and 1 represents a closed square. We fill the grid so that each square is open with probability $p$. Here is one way to do it:

In [44]:
# use numpy to generate a matrix of random numbers between 0 and 1, then convert to either 0 or 1
grid = (numpy.random.rand(n, n) > p).astype(int)
grid

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1, 1, 1]])

Now we need to determine whether there exists a path of open cells from the top to the bottom of the grid.

_How should we do this? What sort of algorithm would work best?_

## Depth-First Search

We will use a depth-first search (DFS) algorithm to determine whether there is an open path from the top of the grid to the bottom. One way to implement this algorithm is to write a recursive function. We will build up to this function in several steps.

__Warm-up:__ Write a recursive function called `search()` that traverses a single column of the grid from top to bottom. 

In [4]:
def search(row):
  print("searching row ", row)
  #search the next square
  if row + 1 < n:
    search(row + 1)
  print("finished searching row ", row)
  
search(0)

searching row  0
searching row  1
searching row  2
searching row  3
searching row  4
searching row  5
searching row  6
searching row  7
searching row  8
searching row  9
finished searching row  9
finished searching row  8
finished searching row  7
finished searching row  6
finished searching row  5
finished searching row  4
finished searching row  3
finished searching row  2
finished searching row  1
finished searching row  0


__Next:__ Modify your function so that it also searches all neighboring squares that haven't been searched yet. This will require keeping track of which squares have been searched. For now, don't worry about which squares are open or closed.

In [0]:
########## CODE FROM MATH 242A ##########

# define an exception that will be raised if percolation occurs 
class percolationFound(Exception): 
  pass 

# matrix to indicate which squares have been searched
visited = numpy.zeros((n,n))  # 0 indicates not yet visited

# define the search function
def search(row, col):
  #print("searching row ", row, " and column ", col)
  
  # remember that this square has been visited
  visited[row,col] = 1
  
  # if we are at the bottom row, then stop
  if row == n-1:
    raise percolationFound ## raise an exception to indicate that percolation has been found 
  elif visited[row+1, col] == 0 and grid[row + 1, col]==0: # then search down
    search(row + 1, col)
  
  # search left
  if col > 0 and visited[row, col-1] == 0 and grid[row,col-1]==0:
    search(row, col - 1)
  
  # search right
  if col < n-1 and visited[row, col+1] == 0 and grid[row,col+1]==0:
    search(row, col + 1)
  
  # search up
  if row > 0 and visited[row-1, col] == 0 and grid[row-1,col]==0:
    search(row - 1, col)
  
  #print("finished searching row ", row, " and column ", col)  
  
## defin a function to start searching at each cellin the top row

def findPercolation():
  global visited 
  # matrix to indicate which squares have been searched
  visited = numpy.zeros((n,n))  # 0 indicates not yet visited
  
  try: 
    for i in range(n):
     #if the top cell in the column n is open and not visited, start searching there
     if grid[0,i] == 0 and visited[0,i] == 0:
        search(0,i) 
        
  except percolationFound: 
    #print("percolationFound !")
    return True 
  else: 
    #print("no percolation")
    return False
    

Try it out:

In [52]:
print(grid)
findPercolation()

[[0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0]
 [0 0 0 1 0 1 1 0 1 0]
 [0 0 0 1 0 0 0 1 0 0]
 [1 1 1 0 1 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 1 1]
 [0 1 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 1 1 1 1]]


False

In [0]:
########## CODE FROM MATH 242B ##########

# make an array that remembers which squares have been visited
visited = numpy.zeros((n,n))  #zeros indicate not yet visited

# define the search function
def search(row, col):
  print("searching row ", row, ", col ", col)
  
  # mark this square as visited
  visited[row, col] = 1
  
  
  if row < n-1 and visited[row+1, col] == 0: #search down
    search(row+1, col)
  
  if col > 0 and visited[row, col-1] == 0: #search left
    search(row, col-1)
        
  if col < n-1 and visited[row, col+1] == 0: #search right
    search(row, col+1)
    
  if row > 0 and visited[row-1, col] == 0: #search up
    search(row-1, col)
  
  
  print("finished searching row ", row, " col ", col)

Our search function will visit all of the squares in our grid, as shown below. However, it doesn't (yet) consider which squares are open or closed.

In [7]:
search(0,0)

searching row  0 , col  0
searching row  1 , col  0
searching row  2 , col  0
searching row  3 , col  0
searching row  4 , col  0
searching row  5 , col  0
searching row  6 , col  0
searching row  7 , col  0
searching row  8 , col  0
searching row  9 , col  0
searching row  9 , col  1
searching row  9 , col  2
searching row  9 , col  3
searching row  9 , col  4
searching row  9 , col  5
searching row  9 , col  6
searching row  9 , col  7
searching row  9 , col  8
searching row  9 , col  9
searching row  8 , col  9
searching row  8 , col  8
searching row  8 , col  7
searching row  8 , col  6
searching row  8 , col  5
searching row  8 , col  4
searching row  8 , col  3
searching row  8 , col  2
searching row  8 , col  1
searching row  7 , col  1
searching row  7 , col  2
searching row  7 , col  3
searching row  7 , col  4
searching row  7 , col  5
searching row  7 , col  6
searching row  7 , col  7
searching row  7 , col  8
searching row  7 , col  9
searching row  6 , col  9
searching ro

__Next:__ Modify your code so that it only searches open squares.

__Next:__ Write another function that calls your `search()` function to start at each unvisited square in the top row of the grid.

__Finally:__ Make your code print a message each time it finds a path of percolation. Optionally, modify your code to stop searching the first time it finds a path of percolation.

## Questions

1. How does the probability of percolation depend on $p$, the probability that any individual cell is open?
2. How does the probability of percolation depend on $n$, the size of the grid?