# Percolation

Consider a $n \times n$ grid of squares. Each square is either "open" with probability $p$ or "closed" with probability $1-p$. A liquid is poured on the top of the grid. What is the probability that the liquid will be able to flow from the top of the grid to the bottom through a path of open squares? 

Import some necessary modules:

In [0]:
import random
import math
import numpy

Define variables:

* `n`: the number of rows and columns in the grid
* `p`: probability that a square is "open"

In [0]:
n = 10
p = 0.5

Define a data structure for the $n \times n$ grid. You will need to decide how to represent "open" and "closed" squares in memory. Fill your grid so that each square is "open" with probability $p$.

In [0]:
# one way to do this: create a matrix of zeros, then change some to ones
grid = numpy.zeros((n,n))
for i in range(n):
  for j in range(n):
    r = random.random() # random number in [0,1)
    if r < p:           # change 0 to 1 with probability p
      grid[i,j] = 1
grid

array([[1., 1., 1., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 0., 1., 1.],
       [0., 1., 0., 1., 1., 0., 1., 1., 0., 0.],
       [1., 1., 1., 0., 1., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 1., 1., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 1., 1., 1.]])

In [0]:
# another option: use numpy to generate a matrix of random numbers between 0 and 1, then convert to either 0 or 1
grid = (numpy.random.rand(n, n) < p).astype(int)
grid

array([[1, 1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 1, 1],
       [1, 1, 1, 0, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 1, 1, 0, 1, 1, 0]])

In [0]:
# another option: use numpy.random.choice
numpy.random.choice(2, p=[0.4,0.6], size=(n,n) )

array([[0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1, 1, 1, 0, 0, 1],
       [0, 1, 1, 1, 1, 0, 0, 0, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 1, 1, 0],
       [0, 1, 1, 0, 1, 1, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 0, 0, 1, 1, 0]])

Now we need to determine whether there exists a path of open cells from the top to the bottom of the grid.

_How should we do this? What sort of algorithm would work best?_

__Think about this! Come to class with next time with your ideas for how to do it!__